# Generated by Django 5.2 on 2025-04-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_unknownquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplifierMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('replacement', models.TextField()),
            ],
        ),
    ]
